# Generated by Django 3.2.7 on 2021-12-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appregistery',
            options={'verbose_name': 'app', 'verbose_name_plural': 'Coldbrew apps'},
        ),
        migrations.AlterField(
            model_name='appregistery',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
